### ISSUE TITLE
Onboarding: Newsletters missing settings

### ISSUE THREAD

**Issue by thomasguillot** [Automattic/newspack-plugin#1300]
**Describe the bug**
When enabling Newsletters, instead of seeing the various settings to configure the plugin, you see an `ActionCard`.

_Note: We should probably support the other ESPs and not just Mailchimp_

**To Reproduce**
Activate the plugin using a fresh site

**Screenshots**
![Screenshot 2021-11-25 at 11 03 53](https://user-images.githubusercontent.com/177929/143430524-fc915e53-209c-4d57-9589-59d69456933c.png)

**Comment by thomasguillot** [comment]
This could be related to the fact that:

1. My plugin wasn't built (and not activated)
2. I have NP debug mode enabled so it assumes the plugin is active

I wonder if we should slightly modify the debug to not consider active some crucial plugins

**Comment by adekbadek** [comment]
This is caused by the debug mode (and `newspack-newsletters` plugin inactive) indeed. Debug mode is meant to be used by our team (or other developers) and for debugging only – I wouldn't consider this an issue. 

Debug mode could be changed, though. It was meant to enable testing alpha (or other testing-related) versions. This could be achieved by writing a wrapper around the `is_plugin_active` WP function [used here](https://github.com/Automattic/newspack-plugin/blob/5955469d289841b905d88c20639bb902afe8d647/includes/class-plugin-manager.php#L481-L482). But I would not consider this a high priority item now – feel free to reopen if you'd like to discuss this further.
