### ISSUE TITLE
My account button not shown for admin users

### ISSUE THREAD

**Issue by yogeshbeniwal** [Automattic/newspack-plugin#1913]
**Describe the bug**
My account button is not showing for logged in admin users, users were created before activating reader activation feature. Haven't tested it for editors.

**To Reproduce**
1. Login in as admin user which was created before reader activation feature
2. Notice no My account button in header alongside tertiary menu

**Expected behavior**
On frontend, My account button in header should be shown to all user levels

**Comment by yogeshbeniwal** [comment]
Thank you for response. Any particular reason for that? IMO, irrespective of user privileges of logged in user, all user should be categorised as reader. This will allow admin/editor/author/contributor users to manage their newsletter and other reader related features. WP user privileges are for level of admin section/feature access. So everybody should be reader on frontend and depending on privileges assigned can perform action for site management.

**Comment by miguelpeixe** [comment]
> all user should be categorised as reader

This interpretation can vary per publisher. As a standard practice, it's best to interpret readers as users without privileged access to the site, due to the number of features surrounding this type of account.

This can be changed through 2 filters:

`newspack_reader_user_roles`:
https://github.com/Automattic/newspack-plugin/blob/e094b159742fc12d0b05921b411bbf54545ce7ad/includes/class-reader-activation.php#L323-L328

`newspack_reader_restricted_roles`:
https://github.com/Automattic/newspack-plugin/blob/e094b159742fc12d0b05921b411bbf54545ce7ad/includes/class-reader-activation.php#L334-L339

To better clarify, restricted roles are configured to overwrite any previous definition of a reader and **never** interpret that user role as reader.

**Comment by miguelpeixe** [comment]
To simplify, you can also use the `newspack_is_user_reader` filter to turn every user into a reader:

```php
add_filter( 'newspack_is_user_reader', '__return_true' );
```

**Comment by yogeshbeniwal** [comment]
Newspack is turning out to be a platform itself and customisation by developers will need lots of internal knowledge of how it works :-)

**Comment by miguelpeixe** [comment]
I agree! A lot of tweaks can be better documented :)
