### ISSUE TITLE
Add support for LaterPay

### ISSUE THREAD

**Issue by philipjohn** [Automattic/newspack-plugin#205]
Some publishers will/may want to use [LaterPay](https://www.laterpay.net/), so we should build in support for it into Newspack. Thanks to their plugin and easy-to-use service, this is straightforward. We need to:

1. Add a LaterPay option to the Reader Revenue wizard
1. Use a Plugin Handoff component to install the [LaterPay plugin](https://en-gb.wordpress.org/plugins/laterpay/)
1. Publishers can then follow the instructions to set up and configure everything
1. _Optionally_ we could try to set sensible values for the colour customisation LaterPay offers, based on the colours chosen in the customiser.

**Comment by claudiulodro** [comment]
Reopening because the full integration is not quite complete: we still need to add it to the Reader Revenue wizard, determine whether it makes sense to integrate it with the Donate block, add AMP-compatibility, etc.

**Comment by thrijith** [comment]
> We still need to add it to the Reader Revenue wizard.

What other steps are required apart from adding it to?

https://github.com/Automattic/newspack-plugin/blob/165a9da8c6e4564f7f03d9d745af583b43d615b1/assets/wizards/readerRevenue/index.js#L257-L266

> Determine whether it makes sense to integrate it with the Donate block.

Since version `2.7.0`, LaterPay supports creating Contribution Dialogs ( via `[laterpay_contribution]` shortcode ), in `2.8.0` a Block to add same was added.

I would be happy to help in adding support for the plugin, please let me know in case of any concerns.

**Comment by claudiulodro** [comment]
Oh I must have missed that bit when reviewing :-/ It probably doesn't make sense to require LaterPay as a required plugin for the Reader Revenue wizard, because then users are forced to install and activate LaterPay in order to set up the WooCommerce-based Donation system.

Thanks for the continued interest, @thrijith! :) I don't think the next step is a technical problem; it's more a design problem (cc @thomasguillot). We need to figure out a good UI for selecting and managing multiple possible Reader Revenue options. Maybe something similar to the Advertising wizard would work well?

<img width="438" alt="Screen Shot 2020-01-03 at 9 59 40 AM" src="https://user-images.githubusercontent.com/7317227/71740003-d9b31200-2e0f-11ea-9630-22df8783aae5.png">

The Newspack/WooCommerce option would hand off to the rest of the wizard (like the Google Ad Manager option does now), and the LaterPay option would hand off to the LaterPay settings (like the AdSense option does now).
