### ISSUE TITLE
Top term will not automatically generate

### ISSUE THREAD

**Issue by GrahamWR** [Automattic/newspack-plugin#210]
**Describe the bug**
When composing an article and selecting Category terms, the Top Term will not autopopulate. Instead, the user has to save and exit the article and come back into it before the Top Terms will refresh for selection.

**To Reproduce**
See above

**Screenshots**
N/A

**Expected behavior**
The Top Term should automatically populate as categories and tags are selected. This is the behavior that occurs in the classic editor.

**Comment by adekbadek** [comment]
Assuming the issue is about [Yoast's primary category](https://yoast.com/help/how-to-select-a-primary-category/), I can't reproduce this. After selecting multiple categories, there's the option to select the primary one:

<img width="302" alt="image" src="https://user-images.githubusercontent.com/7383192/163571138-bfe787b5-b654-4a12-b88f-4d744c3054a8.png">
