### ISSUE TITLE
Newspack plugin vs Newspack theme?

### ISSUE THREAD

**Issue by thelonious89** [Automattic/newspack-plugin#297]
What's the difference between the theme and plugin? Can we use one without the other? Or must they be used together?

**Comment by laurelfulford** [comment]
Hi @thelonious89,

The Newspack Plugin and theme are designed to be used together, but they will also work separately -- if you just want to use one, you can!

The Newspack Plugin will help install and setup a handful of recommended plugins and the Newspack theme, but you can still use a different theme if you like.

The Newspack theme is also designed to be used with the Newspack Blocks (https://github.com/automattic/newspack-blocks), but primarily because the theme has a wide, empty template for the static front page, so you can use the blocks to lay it out, and has some special styles for those blocks. It will work fine without the blocks, too!

I hope this helps! I'm going to close this issue, but if you have any follow up questions around this, please comment here. Thanks!
