### ISSUE TITLE
Components: Checklist 

### ISSUE THREAD

**Issue by sonjaleix** [Automattic/newspack-plugin#31]
A checklist consists of a number of checklist items for the user to work through. Each checklist item can have one of three states: 
1. Next task ––active (has an action button
1.1 Might have a secondary action (e.g. skip stop option)
2. Upcoming task ––inactive (has no action button)
3. Completed task ––checked (has a secondary action to adjust configuration

<img width="876" alt="checklist-full" src="https://user-images.githubusercontent.com/4823744/57169617-061c1780-6dc5-11e9-9f38-8c41896d4470.png">

Example of 3. Completed task and 1.1. List item with secondary action 
<img width="872" alt="example of 3 (completed task) and 1 1 (secondary action)" src="https://user-images.githubusercontent.com/4823744/57169620-0ae0cb80-6dc5-11e9-80f8-2e356e85ddd7.png">

**Comment by jeffersonrabb** [comment]
For reference: 

https://wpcalypso.wordpress.com/devdocs/design/checklist
https://github.com/Automattic/wp-calypso/tree/master/client/components/checklist

**Comment by claudiulodro** [comment]
Since each item in the checklist is a link to a stand-alone SPA, I'm inclined to think this should be a regular, non-SPA page that just links out to the SPAs.

We shouldn't build something exactly like this, but the eCommerce plan checklist is fully PHP, and that's here as an example: https://github.com/Automattic/wc-calypso-bridge/blob/master/includes/class-wc-calypso-bridge-admin-setup-checklist.php We could just copy + paste the CSS and general "checklist handling" for that and be pretty much in business.

**Comment by jeffersonrabb** [comment]
I'm inclined to build it as a React component just to unify our approach. It won't be terribly difficult, and I'll build it so that the JSX matches Calypso's, even though it probably won't have all the functionality of the Calypso components. Then later, if we establish a path to importing Calypso components, all we'll need to do is change the  import.

**Comment by claudiulodro** [comment]
See #32 for info on how the top bar of the checklist should function.

**Comment by claudiulodro** [comment]
Blocked by #45 and #35
