### ISSUE TITLE
Automatically put trending posts at top of homepage posts block

### ISSUE THREAD

**Issue by kn0wsnothing** [Automattic/newspack-plugin#498]
**Is your feature request related to a problem? Please describe.**
I'd like to be able to automatically highlight posts that are trending (ie, getting a high proportion of site traffic).

**Describe the solution you'd like**
Add a setting the home page block to display trending posts.

**Describe alternatives you've considered**
Manually setting the story.

**Additional context**

**Comment by laurelfulford** [comment]
Thanks for adding this, @kn0wsnothing! I've moved over these details to an existing enhancement request in our block repo, just for housekeeping. You can see that issue here: https://github.com/Automattic/newspack-blocks/issues/49

I'm going to close this copy of the issue, but if you have any questions at all about this, just let me know!
