### ISSUE TITLE
Install Wizard: Invalid JSON response when installing Newspack Blocks

### ISSUE THREAD

**Issue by laurelfulford** [Automattic/newspack-plugin#512]
The following error was thrown when installing the Newspack Blocks plugin with the Newspack Plugin:

![image](https://user-images.githubusercontent.com/177561/80042995-53513780-84b5-11ea-8acd-d56c544f6fb3.png)

Refreshing the installer updated the Install link for that plugin to say Activate, but clicking that link didn't do anything. The Newspack Block plugin would only be activated from the WP Admin > Plugins screen. 

This was reported by @joelwills when testing out the plugin; I haven't been able to reproduce it, but I'm probably missing the right conditions. Joel, if you could add any other details of your setup below, or anything I might have missed, it'd be a big help -- thank you!

**Comment by jeffersonrabb** [comment]
I have definitely seen this before sporadically. I've never been able to reproduce consistently.

**Comment by joelwills** [comment]
Thanks Laurel! Just to be clear on my process, I:

- Created a new WordPress.com site
- Upgraded it to Business
- Went to Plugins and installed the Newspack plugin to start the process to convert the site to Atomic
- After it uploaded and the site was converted, the first issue I actually got was the incorrect Plugins page being displayed:
![Screen Shot 2020-04-22 at 11 48 25](https://user-images.githubusercontent.com/3228004/80117433-095f6480-853c-11ea-908e-063c70b4eb44.png)
- After manually going to the correct plugins URL (in Calypso, not wp-admin) all looked fine and I started the wizard
- Step 5, as shown above, is where I got stuck, I couldn't go forwards with this error. On the Plugins page above I manually activated Newspack Blocks and then all went fine.

Hope that helps!

**Comment by iuravic** [comment]
I did a full test to try and reproduce this, but this issue is now out of date. Bot the Wizard and a lot of the Plugin have been updated since this issue was spotted, last over a year ago.

Here's how and what I tested:
- set up a fresh new site, with the latest WP 5.8, and the latest release of the Newspack Plugin
- activated the Newspack Plugin, and was taken to the Wizard with the _"Installing... We are now installing core plugins."_ message:
![image](https://user-images.githubusercontent.com/29167323/128630467-c3dba1d8-d026-44cf-9c4f-829bc555ffb3.png)
- the Wizard completed, and a view at the Plugins showed that Newspack Blocks was installed and activated well
![image](https://user-images.githubusercontent.com/29167323/128630480-595a94aa-8dc7-4451-afbe-710871392d37.png)
