### ISSUE TITLE
Reader Revenue: Investigate configuring Apple Pay with Stripe

### ISSUE THREAD

**Issue by laurelfulford** [Automattic/newspack-plugin#542]
Right now when you enable the WooCommerce Stripe Gateway plugin, you get the following message on your WordPress Dashboard:

![image](https://user-images.githubusercontent.com/177561/82597470-de2d5c80-9b5d-11ea-8043-6b2ebb6d73f7.png)

The Stripe plugin allows you to also take payments from Apple Pay, but needs additional configuration -- we need to figure out exactly what that additional configuration is so we can (ideally) set it up automatically on sites using this plugin, to prevent errors.

**Comment by adekbadek** [comment]
I believe this is about the same configuration what was done for Stripe (as Reader Revenue platform) in https://github.com/Automattic/newspack-plugin/pull/1305:

1. [responding to a verification file request](https://github.com/Automattic/newspack-plugin/pull/1305/files#diff-801bd383c9c38a05b4ae27e9aad0ac07aeea35d15498abec76f1c9db6c114260R714-R729)
2. [adding the domain on Stripe](https://github.com/Automattic/newspack-plugin/pull/1305/files#diff-801bd383c9c38a05b4ae27e9aad0ac07aeea35d15498abec76f1c9db6c114260R758-R782)

Because `Stripe_Connection` class is loaded regardless of the chosen Reader Revenue platform, these actions will be fired, so this issue is actually closed by #1305.
