### ISSUE TITLE
Add Election Kit to supported plugins

### ISSUE THREAD

**Issue by philipjohn** [Automattic/newspack-plugin#676]
**Is your feature request related to a problem? Please describe.**
The plugin appears as an "unsupported plugin" in the health check even though we support it.

**Describe the solution you'd like**
The plugin should be added to the supported plugins list, and not appear in the health check.

**Comment by adekbadek** [comment]
Same for Republication Tracker Tool. But in order not to clutter the plugins screen, some plugins should pass Health Check, but not necessarily appear on the plugins screen.

**Comment by tmmbecker** [comment]
Even better, it would be good for us to come up with a more formal process to determine if a plugin should be included in the plugins screen. I think we're quickly approaching too much, which makes it hard for folks to find what's meaningful.

**Comment by adekbadek** [comment]
Since [Election Kit](https://github.com/Automattic/newspack-electionkit/) is prefixed with `newspack-`, it won't be added to the unsupported plugins list - closing the issue.

@tmmbecker - #1139 adds the whitelist of plugins which will not be marked as unsupported, but won't show up on WP Admin plugins screen (if uninstalled) either.
